from __future__ import annotations


DEMO_CONNECTOR_READINESS_SEEDS = [
    {
        "connector_id": "gmail_read_review",
        "connector_name": "Gmail Read Review",
        "provider": "Gmail",
        "purpose": "Review email metadata/content for manual triage planning after explicit approval.",
        "required_permissions": ["gmail.readonly", "manual mailbox scope review"],
        "data_access_level": "read_only_content",
        "write_access": False,
        "risk_level": "medium",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": True,
        "rollback_plan": ["Revoke OAuth grant", "Disable mailbox scopes", "Return to local demo records"],
        "test_plan": ["Use synthetic email fixtures", "Verify no send/delete/archive calls", "Review scope list manually"],
        "safety_gates": ["Explicit user approval", "Read-only scope only", "No credential logging"],
        "readiness_status": "design_only",
        "recommended_next_step": "Keep Gmail read review in design-only mode until approval and fixture tests exist.",
    },
    {
        "connector_id": "gmail_draft_creation",
        "connector_name": "Gmail Draft Creation",
        "provider": "Gmail",
        "purpose": "Prepare draft replies for manual review without sending.",
        "required_permissions": ["gmail.compose", "draft create only"],
        "data_access_level": "write_limited",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": False,
        "rollback_plan": ["Delete demo drafts manually", "Disable compose scope", "Fall back to local text drafts"],
        "test_plan": ["Generate local draft text only", "Confirm no send endpoint is reachable", "Check audit log wording"],
        "safety_gates": ["Draft-only guard", "Manual review before use", "No live OAuth in this stage"],
        "readiness_status": "blocked_until_approved",
        "recommended_next_step": "Model draft creation as local text output before any Gmail compose scope is considered.",
    },
    {
        "connector_id": "gmail_send",
        "connector_name": "Gmail Send",
        "provider": "Gmail",
        "purpose": "Send email messages from an Agent workflow.",
        "required_permissions": ["gmail.send"],
        "data_access_level": "write_sensitive",
        "write_access": True,
        "risk_level": "blocked",
        "approval_required": True,
        "demo_mode_available": False,
        "read_only_mode_available": False,
        "rollback_plan": ["Revoke send scope", "Disable connector", "Require manual incident review"],
        "test_plan": ["Do not call send API", "Keep fixture-only tests", "Confirm blocked status in policy checks"],
        "safety_gates": ["Explicit approval gate", "Manual send confirmation", "Rollback path before enablement"],
        "readiness_status": "blocked_until_approved",
        "recommended_next_step": "Keep Gmail send blocked until a separate approval workflow and audit trail exists.",
    },
    {
        "connector_id": "google_sheets_read",
        "connector_name": "Google Sheets Read",
        "provider": "Google Sheets",
        "purpose": "Read structured rows for dashboard or report context.",
        "required_permissions": ["spreadsheets.readonly"],
        "data_access_level": "read_only_content",
        "write_access": False,
        "risk_level": "medium",
        "approval_required": False,
        "demo_mode_available": True,
        "read_only_mode_available": True,
        "rollback_plan": ["Use CSV fixture instead", "Remove sheet URL from config", "Disable read scope"],
        "test_plan": ["Use local CSV mirror", "Validate schema mapping", "Confirm no write endpoint is used"],
        "safety_gates": ["Read-only scope", "No private sheet data in screenshots", "Local fixture fallback"],
        "readiness_status": "ready_for_demo",
        "recommended_next_step": "Prototype with local CSV first; Sheets read-only is the safest future connector candidate.",
    },
    {
        "connector_id": "google_sheets_write",
        "connector_name": "Google Sheets Write",
        "provider": "Google Sheets",
        "purpose": "Write Agent summaries into a spreadsheet.",
        "required_permissions": ["spreadsheets.write"],
        "data_access_level": "write_limited",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": False,
        "rollback_plan": ["Restore sheet backup", "Disable write scope", "Use local export instead"],
        "test_plan": ["Use throwaway fixture sheet only after approval", "Assert no production sheet ID", "Check write diff preview"],
        "safety_gates": ["Write preview", "Explicit sheet allowlist", "Manual approval before write"],
        "readiness_status": "blocked_until_approved",
        "recommended_next_step": "Keep Sheets write blocked until read-only sync and write preview are proven.",
    },
    {
        "connector_id": "google_drive_read",
        "connector_name": "Google Drive Read",
        "provider": "Google Drive",
        "purpose": "Read selected Drive file metadata or approved public-safe documents.",
        "required_permissions": ["drive.readonly", "file allowlist"],
        "data_access_level": "read_only_content",
        "write_access": False,
        "risk_level": "medium",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": True,
        "rollback_plan": ["Remove file allowlist", "Revoke Drive scope", "Use local document fixtures"],
        "test_plan": ["Use local sample docs", "Validate allowlist behavior", "Confirm no folder-wide scan"],
        "safety_gates": ["File allowlist", "No private docs in public UI", "No token logging"],
        "readiness_status": "needs_review",
        "recommended_next_step": "Design file allowlists before any Drive read connector is considered.",
    },
    {
        "connector_id": "notion_database_write",
        "connector_name": "Notion Database Write",
        "provider": "Notion",
        "purpose": "Write structured Agent summaries into a Notion database.",
        "required_permissions": ["notion database write", "database allowlist"],
        "data_access_level": "write_sensitive",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": False,
        "rollback_plan": ["Archive created pages", "Disable integration token", "Use Markdown export instead"],
        "test_plan": ["Generate local Markdown preview", "Validate database schema mapping", "Block live token use"],
        "safety_gates": ["Database allowlist", "Manual page preview", "No real integration token in repo"],
        "readiness_status": "blocked_until_approved",
        "recommended_next_step": "Keep Notion write as a design-only future connector until preview and approval gates exist.",
    },
    {
        "connector_id": "airtable_crm_sync",
        "connector_name": "Airtable CRM Sync",
        "provider": "Airtable",
        "purpose": "Sync structured CRM or workflow rows between AgentHub and Airtable.",
        "required_permissions": ["airtable base read/write", "base allowlist"],
        "data_access_level": "write_sensitive",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": True,
        "rollback_plan": ["Use Airtable revision history", "Disable base token", "Revert to local CSV export"],
        "test_plan": ["Use local CSV CRM fixture", "Validate field mapping", "Require dry-run diff before write"],
        "safety_gates": ["Base allowlist", "Dry-run diff", "Manual approval before sync"],
        "readiness_status": "blocked_until_approved",
        "recommended_next_step": "Design Airtable sync as CSV-first before any live base write is considered.",
    },
    {
        "connector_id": "telegram_alert",
        "connector_name": "Telegram Alert",
        "provider": "Telegram",
        "purpose": "Send notification summaries to a Telegram chat.",
        "required_permissions": ["bot sendMessage", "chat allowlist"],
        "data_access_level": "write_limited",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": False,
        "rollback_plan": ["Disable bot token", "Remove chat allowlist", "Use local notification preview"],
        "test_plan": ["Render alert preview text", "Use fake chat ID fixture", "Assert no sendMessage call"],
        "safety_gates": ["Chat allowlist", "Manual send approval", "No bot token loaded"],
        "readiness_status": "needs_review",
        "recommended_next_step": "Demo Telegram alerts as local preview text before any live send connector.",
    },
    {
        "connector_id": "github_status_read",
        "connector_name": "GitHub Status Read",
        "provider": "GitHub",
        "purpose": "Read public repository status, issues, or release metadata.",
        "required_permissions": ["public_repo read"],
        "data_access_level": "read_only_metadata",
        "write_access": False,
        "risk_level": "low",
        "approval_required": False,
        "demo_mode_available": True,
        "read_only_mode_available": True,
        "rollback_plan": ["Disable GitHub status card", "Use cached public URL metadata", "Keep manual repo link"],
        "test_plan": ["Use static GitHub metadata fixture", "Validate no write scopes", "Confirm no token required"],
        "safety_gates": ["Public metadata only", "No private repo token", "No mutation endpoint"],
        "readiness_status": "ready_for_demo",
        "recommended_next_step": "Keep GitHub status read public-only and token-free for the first connector demo.",
    },
    {
        "connector_id": "github_push_release",
        "connector_name": "GitHub Push / Release",
        "provider": "GitHub",
        "purpose": "Push commits, tags, or releases from an Agent workflow.",
        "required_permissions": ["repo write", "contents write", "release write"],
        "data_access_level": "write_sensitive",
        "write_access": True,
        "risk_level": "blocked",
        "approval_required": True,
        "demo_mode_available": False,
        "read_only_mode_available": False,
        "rollback_plan": ["Revert commit manually", "Revoke token", "Disable release automation"],
        "test_plan": ["Do not push from AgentHub", "Keep local git status display only", "Require explicit user-run git commands"],
        "safety_gates": ["No git push from UI", "No remote mutation", "Explicit user approval outside AgentHub"],
        "readiness_status": "blocked_until_approved",
        "recommended_next_step": "Keep GitHub push/release blocked; AgentHub may only show status and manual guidance.",
    },
    {
        "connector_id": "n8n_webhook",
        "connector_name": "n8n Webhook",
        "provider": "n8n",
        "purpose": "Send structured Agent events into an n8n workflow.",
        "required_permissions": ["webhook URL", "payload schema"],
        "data_access_level": "write_limited",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": False,
        "rollback_plan": ["Disable webhook", "Rotate webhook URL", "Use local payload file"],
        "test_plan": ["Generate local JSON payload only", "Validate schema", "Assert no HTTP request is sent"],
        "safety_gates": ["Dry-run payload preview", "Webhook allowlist", "No automatic POST"],
        "readiness_status": "future",
        "recommended_next_step": "Keep n8n as a future dry-run payload design before any HTTP connector.",
    },
    {
        "connector_id": "make_scenario",
        "connector_name": "Make Scenario",
        "provider": "Make",
        "purpose": "Trigger a Make scenario with AgentHub event data.",
        "required_permissions": ["Make webhook URL", "scenario allowlist"],
        "data_access_level": "write_limited",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": False,
        "rollback_plan": ["Disable scenario webhook", "Rotate URL", "Return to local JSON export"],
        "test_plan": ["Preview payload locally", "Validate scenario allowlist", "Do not send HTTP request"],
        "safety_gates": ["Scenario allowlist", "Dry-run payload", "Manual trigger approval"],
        "readiness_status": "future",
        "recommended_next_step": "Keep Make integration as future payload planning only.",
    },
    {
        "connector_id": "zapier_zap",
        "connector_name": "Zapier Zap",
        "provider": "Zapier",
        "purpose": "Trigger a Zapier Zap from AgentHub event metadata.",
        "required_permissions": ["Zapier webhook URL", "zap allowlist"],
        "data_access_level": "write_limited",
        "write_access": True,
        "risk_level": "high",
        "approval_required": True,
        "demo_mode_available": True,
        "read_only_mode_available": False,
        "rollback_plan": ["Disable Zap", "Rotate webhook URL", "Use local event export"],
        "test_plan": ["Generate local event JSON", "Validate payload shape", "Assert no live webhook call"],
        "safety_gates": ["Zap allowlist", "Dry-run preview", "Manual approval before trigger"],
        "readiness_status": "future",
        "recommended_next_step": "Keep Zapier as a future connector plan with dry-run payloads only.",
    },
]
