from __future__ import annotations


DEMO_USEFUL_SIGNAL_SEEDS = [
    {
        "signal_id": "hub_v2_11_manifest_coverage",
        "title": "AgentHubControlCenter V2 has 11 valid Agent manifests",
        "source_agent": "AgentHubControlCenter",
        "source_type": "agent_manifest",
        "category": "project_progress",
        "summary": "The hub can now see the full local portfolio through 11 safe manifest records.",
        "relevance_score": 96,
        "urgency_score": 68,
        "actionability_score": 72,
        "value_score": 94,
        "risk_score": 12,
        "recommended_action": "Use the manifest coverage as the baseline for signal ranking and portfolio decisions.",
        "target_agent": "AgentHubControlCenter",
        "status": "reviewed",
        "related_action_id": "view_agent_manifest",
    },
    {
        "signal_id": "codex_prompt_generator_complete",
        "title": "Codex Prompt Generator can improve project handoff speed",
        "source_agent": "AgentHubControlCenter",
        "source_type": "codex_prompt_generator",
        "category": "workflow_automation",
        "summary": "The hub can generate copy-ready Codex prompts without sending or executing anything automatically.",
        "relevance_score": 92,
        "urgency_score": 70,
        "actionability_score": 82,
        "value_score": 90,
        "risk_score": 18,
        "recommended_action": "Use generated prompts for safe next-stage planning and keep them copy-only.",
        "target_agent": "AgentHubControlCenter",
        "status": "reviewed",
        "related_action_id": "generate_codex_prompt",
    },
    {
        "signal_id": "useful_signals_engine_next_brain",
        "title": "Useful Signals Engine is the next decision layer",
        "source_agent": "AgentHubControlCenter",
        "source_type": "project_status",
        "category": "action_required",
        "summary": "The hub needs a ranking layer so the user sees high-value signals instead of raw project metadata.",
        "relevance_score": 98,
        "urgency_score": 90,
        "actionability_score": 88,
        "value_score": 96,
        "risk_score": 15,
        "recommended_action": "Complete HUB-V2-007 with schema, scoring, filters, recommendations, and UI cards.",
        "target_agent": "AgentHubControlCenter",
        "status": "needs_action",
        "related_action_id": "view_project_status",
    },
    {
        "signal_id": "connector_readiness_not_live_yet",
        "title": "Connector readiness is useful, but live accounts should stay disconnected",
        "source_agent": "AgentHubControlCenter",
        "source_type": "action_registry",
        "category": "risk_warning",
        "summary": "Gmail, Google Sheets, Notion, Airtable, Telegram, and other connectors need approval gates before any live access.",
        "relevance_score": 94,
        "urgency_score": 82,
        "actionability_score": 78,
        "value_score": 86,
        "risk_score": 92,
        "recommended_action": "Keep connector work as readiness planning until a separate approved connector stage.",
        "target_agent": "AgentHubControlCenter",
        "status": "watchlist",
        "related_action_id": "send_to_agent_hub",
    },
    {
        "signal_id": "video_extract_content_source",
        "title": "VideoExtractSkill can become a content extraction input source",
        "source_agent": "VideoExtractSkill",
        "source_type": "agent_manifest",
        "category": "workflow_automation",
        "summary": "Video and image extraction can feed future notes, reports, or knowledge workflows after manual review.",
        "relevance_score": 82,
        "urgency_score": 48,
        "actionability_score": 68,
        "value_score": 84,
        "risk_score": 34,
        "recommended_action": "Keep it as a manual input source; do not process private media inside AgentHub.",
        "target_agent": "VideoExtractSkill",
        "status": "watchlist",
        "related_action_id": "view_latest_report",
    },
    {
        "signal_id": "personal_knowledge_long_term_memory",
        "title": "PersonalKnowledgeAgent is a long-term knowledge sediment target",
        "source_agent": "PersonalKnowledgeAgent",
        "source_type": "agent_manifest",
        "category": "learning_value",
        "summary": "The knowledge workflow can store public-safe project learnings and retrieval plans later.",
        "relevance_score": 80,
        "urgency_score": 42,
        "actionability_score": 58,
        "value_score": 82,
        "risk_score": 45,
        "recommended_action": "Keep it on the watchlist until a public-safe knowledge ingestion stage is explicitly requested.",
        "target_agent": "PersonalKnowledgeAgent",
        "status": "watchlist",
        "related_action_id": "view_agent_manifest",
    },
    {
        "signal_id": "social_pain_business_opportunity_source",
        "title": "SocialPainFinderAgent is a business opportunity source",
        "source_agent": "SocialPainFinderAgent",
        "source_type": "agent_manifest",
        "category": "business_opportunity",
        "summary": "Pain point and opportunity scoring can feed future portfolio positioning and consulting demos.",
        "relevance_score": 86,
        "urgency_score": 55,
        "actionability_score": 68,
        "value_score": 90,
        "risk_score": 28,
        "recommended_action": "Use it as a source of public-safe opportunity signals, not as a live social scraper.",
        "target_agent": "SocialPainFinderAgent",
        "status": "reviewed",
        "related_action_id": "export_summary",
    },
    {
        "signal_id": "sme_ops_recommendation_pair",
        "title": "BusinessOpsAgent and NextOpsAgent can power SME recommendations",
        "source_agent": "BusinessOpsAgent",
        "source_type": "local_csv",
        "category": "workflow_automation",
        "summary": "Operations and workflow diagnosis agents can form a strong SME consulting-style recommendation flow.",
        "relevance_score": 90,
        "urgency_score": 60,
        "actionability_score": 74,
        "value_score": 92,
        "risk_score": 24,
        "recommended_action": "Keep the pair as a future workflow bundle and show recommendations as text only.",
        "target_agent": "NextOpsAgent",
        "status": "reviewed",
        "related_action_id": "view_latest_report",
    },
    {
        "signal_id": "market_news_signal_sources",
        "title": "MarketSenseAgent and NewsSignalAgent can become market signal sources",
        "source_agent": "MarketSenseAgent",
        "source_type": "report",
        "category": "workflow_automation",
        "summary": "Market and news agents can provide public-safe signal summaries for future portfolio intelligence views.",
        "relevance_score": 84,
        "urgency_score": 52,
        "actionability_score": 62,
        "value_score": 84,
        "risk_score": 50,
        "recommended_action": "Keep all finance/news signals educational and display-only; do not enable trading or live alerts.",
        "target_agent": "NewsSignalAgent",
        "status": "watchlist",
        "related_action_id": "view_latest_report",
    },
    {
        "signal_id": "career_pilot_job_signal_source",
        "title": "CareerPilotAgent can provide job-search workflow signals",
        "source_agent": "CareerPilotAgent",
        "source_type": "agent_manifest",
        "category": "learning_value",
        "summary": "Career workflow data can become a useful planning signal while staying disconnected from real Gmail or job platforms.",
        "relevance_score": 72,
        "urgency_score": 38,
        "actionability_score": 54,
        "value_score": 72,
        "risk_score": 42,
        "recommended_action": "Keep the project paused after showcase; only use metadata-level signals in AgentHub.",
        "target_agent": "CareerPilotAgent",
        "status": "watchlist",
        "related_action_id": "view_project_status",
    },
    {
        "signal_id": "github_showcase_screenshots_after_v2_stability",
        "title": "GitHub showcase screenshots should refresh after V2 stabilizes",
        "source_agent": "AgentHubControlCenter",
        "source_type": "project_status",
        "category": "portfolio_improvement",
        "summary": "The public README screenshots should eventually include the new Action Center and Useful Signals surfaces.",
        "relevance_score": 78,
        "urgency_score": 58,
        "actionability_score": 72,
        "value_score": 82,
        "risk_score": 18,
        "recommended_action": "Refresh screenshots only after the V2 Useful Signals UI is stable and public-safe.",
        "target_agent": "AgentHubControlCenter",
        "status": "watchlist",
        "related_action_id": "refresh_screenshots",
    },
    {
        "signal_id": "high_risk_connectors_require_approval",
        "title": "High-risk connector execution must require explicit approval",
        "source_agent": "AgentHubControlCenter",
        "source_type": "action_registry",
        "category": "risk_warning",
        "summary": "Sending email, deleting files, modifying git remotes, pushing code, or connecting real accounts must stay blocked.",
        "relevance_score": 96,
        "urgency_score": 88,
        "actionability_score": 80,
        "value_score": 90,
        "risk_score": 98,
        "recommended_action": "Keep all high-risk connector or execution actions blocked until a separate approval stage exists.",
        "target_agent": "AgentHubControlCenter",
        "status": "needs_action",
        "related_action_id": "git_push",
    },
    {
        "signal_id": "idea_score_can_rank_future_projects",
        "title": "IdeaScoreAgent can help rank future project ideas",
        "source_agent": "IdeaScoreAgent",
        "source_type": "manual_demo_data",
        "category": "business_opportunity",
        "summary": "Transparent idea scoring can help choose portfolio extensions without overbuilding too early.",
        "relevance_score": 78,
        "urgency_score": 45,
        "actionability_score": 66,
        "value_score": 80,
        "risk_score": 22,
        "recommended_action": "Use idea scoring as a planning input only; do not expand completed projects automatically.",
        "target_agent": "IdeaScoreAgent",
        "status": "reviewed",
        "related_action_id": "export_summary",
    },
    {
        "signal_id": "social_packaging_not_current_priority",
        "title": "Social packaging is not the current AgentHub priority",
        "source_agent": "AgentHubControlCenter",
        "source_type": "manual_demo_data",
        "category": "portfolio_improvement",
        "summary": "The current stage should stay focused on GitHub portfolio quality and safe local product surfaces, not social media packaging.",
        "relevance_score": 42,
        "urgency_score": 18,
        "actionability_score": 24,
        "value_score": 36,
        "risk_score": 24,
        "recommended_action": "Keep this ignored unless the user explicitly requests social content, resume packaging, or commercialization work.",
        "target_agent": "AgentHubControlCenter",
        "status": "ignored",
        "related_action_id": "none",
    },
]
