from __future__ import annotations


READY_AGENT_NAMES = [
    "AgentHubControlCenter",
    "BusinessOpsAgent",
    "CareerPilotAgent",
    "IdeaScoreAgent",
    "MarketSenseAgent",
    "NewsSignalAgent",
    "NextOpsAgent",
    "PersonalKnowledgeAgent",
    "QuantLabAgent",
    "SocialPainFinderAgent",
    "VideoExtractSkill",
]


DEMO_WORKFLOW_SIMULATION_SEEDS = [
    {
        "workflow_id": "project_progress_review",
        "workflow_name": "Project Progress Review Workflow",
        "workflow_type": "project_review",
        "input_source": "agent_manifest + PROJECT_STATUS + README + Action Center",
        "source_agents": READY_AGENT_NAMES,
        "signals_used": [
            "Manifest coverage across 11 Agents",
            "Project review workflow can summarize next steps across 11 agents",
            "Action Center local metadata",
        ],
        "recommended_actions": [
            "view_project_status",
            "view_agent_manifest",
            "export_summary",
        ],
        "approval_gates": [
            {
                "gate_id": "project_review_display_gate",
                "gate_name": "Project review display-only gate",
                "target_action_id": "view_project_status",
                "target_connector_id": "none",
                "risk_level": "low",
                "approval_required": False,
                "approval_status": "not_required",
                "required_checks": [
                    "Use local project metadata only",
                    "Do not read .env or private outputs",
                    "Do not execute child project scripts",
                ],
                "dry_run_required": False,
                "rollback_required": False,
                "human_review_required": False,
                "block_reason": "No block. Display-only local review.",
                "allowed_execution_mode": "display_only",
            }
        ],
        "blocked_steps": [],
        "manual_steps": [
            "Open My Tools / Agent Registry and confirm 11 Agents are visible.",
            "Review Useful Signals and Action Center cards.",
            "Copy the summary into a manual report if needed.",
        ],
        "generated_outputs": [
            "Project progress summary",
            "Manual next-step checklist",
            "Public-safe summary report text",
        ],
        "risk_summary": "Low risk because it reads already-loaded metadata and does not execute actions.",
        "next_recommended_step": "Use the workflow card to review next steps across the 11 local Agents.",
    },
    {
        "workflow_id": "useful_signals_review",
        "workflow_name": "Useful Signals Review Workflow",
        "workflow_type": "signal_review",
        "input_source": "Useful Signals Engine + local demo metadata + Action Center",
        "source_agents": [
            "AgentHubControlCenter",
            "BusinessOpsAgent",
            "SocialPainFinderAgent",
            "NextOpsAgent",
            "PersonalKnowledgeAgent",
        ],
        "signals_used": [
            "Top 5 Useful Signals",
            "Needs Action signals",
            "Watchlist signals",
            "Workflow-generated useful signals",
        ],
        "recommended_actions": [
            "review_signal_cards",
            "view_agent_manifest",
            "generate_codex_prompt",
        ],
        "approval_gates": [
            {
                "gate_id": "signal_review_manual_gate",
                "gate_name": "Signal review manual-only gate",
                "target_action_id": "review_signal_cards",
                "target_connector_id": "none",
                "risk_level": "medium",
                "approval_required": True,
                "approval_status": "ready_for_manual_review",
                "required_checks": [
                    "Confirm the signal is display-only",
                    "Confirm recommended action is not auto-run",
                    "Keep high-risk recommendations in manual review",
                ],
                "dry_run_required": False,
                "rollback_required": False,
                "human_review_required": True,
                "block_reason": "Manual review required before turning signals into future actions.",
                "allowed_execution_mode": "manual_only",
            }
        ],
        "blocked_steps": [],
        "manual_steps": [
            "Filter Useful Signals by category and status.",
            "Read why_important and suggested_next_step before acting.",
            "Move only text instructions into Manual Runbook or Codex Prompt Generator.",
        ],
        "generated_outputs": [
            "Prioritized useful signal review",
            "Manual action shortlist",
            "Codex prompt candidate text",
        ],
        "risk_summary": "Medium risk because signals may recommend future work, but no recommendation is executed.",
        "next_recommended_step": "Review needs-action signals and convert safe items into copy-ready prompts only.",
    },
    {
        "workflow_id": "connector_readiness_review",
        "workflow_name": "Connector Readiness Review Workflow",
        "workflow_type": "connector_review",
        "input_source": "Connector Readiness Simulator + Action Safety Policy + Useful Signals",
        "source_agents": ["AgentHubControlCenter"],
        "signals_used": [
            "Gmail Send readiness needs review",
            "Google Sheets Read readiness needs review",
            "Telegram Alert readiness needs review",
            "Connector approval gates should block Gmail Send and GitHub Push",
        ],
        "recommended_actions": [
            "review_connector_readiness",
            "review_action_safety_policy",
            "plan_approval_gates",
        ],
        "approval_gates": [
            {
                "gate_id": "gmail_send_block_gate",
                "gate_name": "Block Gmail Send",
                "target_action_id": "send_email",
                "target_connector_id": "gmail_send",
                "risk_level": "blocked",
                "approval_required": True,
                "approval_status": "blocked",
                "required_checks": [
                    "No OAuth flow exists",
                    "No gmail.send scope is loaded",
                    "No send API call is allowed",
                    "Human review and rollback plan required before any future stage",
                ],
                "dry_run_required": True,
                "rollback_required": True,
                "human_review_required": True,
                "block_reason": "Sending email is a high-impact real-world action and must stay blocked.",
                "allowed_execution_mode": "blocked",
            },
            {
                "gate_id": "github_push_release_block_gate",
                "gate_name": "Block GitHub Push / Release",
                "target_action_id": "git_push",
                "target_connector_id": "github_push_release",
                "risk_level": "blocked",
                "approval_required": True,
                "approval_status": "blocked",
                "required_checks": [
                    "No git remote mutation from AgentHub",
                    "No push token loaded",
                    "No release endpoint or command execution",
                    "Manual user-run git command required outside AgentHub",
                ],
                "dry_run_required": True,
                "rollback_required": True,
                "human_review_required": True,
                "block_reason": "Git push or release automation can mutate public repositories and must stay blocked.",
                "allowed_execution_mode": "blocked",
            },
            {
                "gate_id": "google_sheets_read_dry_run_gate",
                "gate_name": "Google Sheets Read dry-run gate",
                "target_action_id": "read_sheet_metadata",
                "target_connector_id": "google_sheets_read",
                "risk_level": "medium",
                "approval_required": True,
                "approval_status": "ready_for_manual_review",
                "required_checks": [
                    "Use local CSV fixture first",
                    "Confirm read-only scope only",
                    "Do not load credentials in HUB-V2-009",
                ],
                "dry_run_required": True,
                "rollback_required": False,
                "human_review_required": True,
                "block_reason": "Read-only connector can be planned, but live access is not enabled.",
                "allowed_execution_mode": "dry_run_only",
            },
        ],
        "blocked_steps": [
            "Gmail Send",
            "GitHub Push / Release",
        ],
        "manual_steps": [
            "Open Connectors and filter blocked/high-risk connectors.",
            "Review required permissions and safety gates.",
            "Keep all connector outputs as metadata-only planning notes.",
        ],
        "generated_outputs": [
            "Connector approval gate table",
            "Blocked connector summary",
            "Manual connector rollout notes",
        ],
        "risk_summary": "High risk because send, push, webhook, and write connectors can mutate external systems.",
        "next_recommended_step": "Keep Gmail Send and GitHub Push blocked; use Google Sheets Read only as local CSV dry-run planning.",
    },
    {
        "workflow_id": "codex_handoff",
        "workflow_name": "Codex Handoff Workflow",
        "workflow_type": "codex_handoff",
        "input_source": "Codex Prompt Generator + Manual Runbook + Action Center + PROJECT_STATUS",
        "source_agents": ["AgentHubControlCenter"],
        "signals_used": [
            "Codex handoff workflow is ready for manual use",
            "Current checkpoint",
            "Next recommended action",
        ],
        "recommended_actions": [
            "generate_codex_prompt",
            "view_project_status",
            "view_agent_manifest",
        ],
        "approval_gates": [
            {
                "gate_id": "codex_prompt_template_gate",
                "gate_name": "Codex prompt template-only gate",
                "target_action_id": "generate_codex_prompt",
                "target_connector_id": "none",
                "risk_level": "low",
                "approval_required": False,
                "approval_status": "approved_demo_only",
                "required_checks": [
                    "Prompt is copy-ready text only",
                    "Do not auto-send prompt to Codex",
                    "Do not execute generated instructions from AgentHub",
                ],
                "dry_run_required": False,
                "rollback_required": False,
                "human_review_required": False,
                "block_reason": "No block. Template-only handoff text is safe for manual copy.",
                "allowed_execution_mode": "template_only",
            }
        ],
        "blocked_steps": [],
        "manual_steps": [
            "Select AgentHubControlCenter in Codex Prompt Generator.",
            "Select continue_next_stage or create_connector_plan prompt type.",
            "Copy the generated prompt manually if it matches the intended stage.",
        ],
        "generated_outputs": [
            "Copy-ready Codex prompt",
            "Manual runbook reference",
            "Completion report checklist",
        ],
        "risk_summary": "Low risk because prompt generation is template-only and no prompt is auto-sent.",
        "next_recommended_step": "Use this workflow to hand off the next stage to Codex manually.",
    },
]
